version: 2

sources:
  - name: northwind
    description: Data from Northwind ERP
    database: curso-etl-101  
    schema: erp_northwind  
    tables:
      - name: orders
        description: This table lists the orders from ERP Northwind
        columns:
          - name: order_id
            description: Unique ID for this table
      - name: customers
        description: This table lists the customers from ERP Northwind
        columns:
          - name: customer_id
            description: Unique ID for this table
      - name: order_details
        description: This table lists the order details from ERP Northwind
